apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: app
  namespace: kubecon-seattle-2018
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/joe-does-knative/github.com/josephburnett/kubecon-seattle-2018/app:latest
            env:
            - name: VERSION
              value: "Hello Kubecon"
